### ISSUE TITLE
マークダウンかけない

### ISSUE THREAD

**Issue by yori3** [wckansai2016/github-test#5]
オシエテ・・・・

**Comment by dsk52** [comment]
この辺見たら良いかと思います 
[Markdown書き方メモ - Qiita](http://qiita.com/Id_Seth/items/b684cfabe0f2fde0c67b)

サービスによって若干使えないものもあるみたいなので、Previewで要確認です👍

**Comment by gouten5010** [comment]
@d-kusk 今テストしてるだけなので大丈夫ですー。
でも情報ありがとう！
